/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ChatSessionId = IDL.Nat;
export const MessageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const DocumentId = IDL.Nat;
export const Citation = IDL.Record({
  'documentName' : IDL.Text,
  'passage' : IDL.Text,
  'documentId' : DocumentId,
  'index' : IDL.Nat,
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : MessageRole,
  'citations' : IDL.Vec(Citation),
});
export const ChatSessionView = IDL.Record({
  'id' : ChatSessionId,
  'title' : IDL.Text,
  'documentIds' : IDL.Vec(DocumentId),
  'messages' : IDL.Vec(Message),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const AskResult = IDL.Record({
  'answer' : Message,
  'session' : ChatSessionView,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileType = IDL.Variant({
  'pdf' : IDL.Null,
  'txt' : IDL.Null,
  'markdown' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ProcessingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'processing' : IDL.Null,
  'ready' : IDL.Null,
  'failed' : IDL.Text,
});
export const DocumentDetail = IDL.Record({
  'id' : DocumentId,
  'status' : ProcessingStatus,
  'name' : IDL.Text,
  'fileType' : FileType,
  'extractedText' : IDL.Opt(IDL.Text),
  'storageRef' : IDL.Text,
  'sizeBytes' : IDL.Nat,
  'uploadedAt' : Timestamp,
});
export const ChatSessionSummary = IDL.Record({
  'id' : ChatSessionId,
  'title' : IDL.Text,
  'documentIds' : IDL.Vec(DocumentId),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'messageCount' : IDL.Nat,
});
export const DocumentFilter = IDL.Record({
  'nameContains' : IDL.Opt(IDL.Text),
  'fileType' : IDL.Opt(FileType),
});
export const DocumentView = IDL.Record({
  'id' : DocumentId,
  'status' : ProcessingStatus,
  'name' : IDL.Text,
  'fileType' : FileType,
  'hasExtractedText' : IDL.Bool,
  'sizeBytes' : IDL.Nat,
  'uploadedAt' : Timestamp,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'askQuestion' : IDL.Func([ChatSessionId, IDL.Text], [AskResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChatSession' : IDL.Func(
      [IDL.Text, IDL.Vec(DocumentId)],
      [ChatSessionView],
      [],
    ),
  'createDocument' : IDL.Func(
      [IDL.Text, FileType, IDL.Nat, IDL.Text],
      [DocumentId],
      [],
    ),
  'deleteChatSession' : IDL.Func([ChatSessionId], [IDL.Bool], []),
  'deleteDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatSession' : IDL.Func(
      [ChatSessionId],
      [IDL.Opt(ChatSessionView)],
      ['query'],
    ),
  'getDocument' : IDL.Func([DocumentId], [IDL.Opt(DocumentDetail)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChatSessions' : IDL.Func([], [IDL.Vec(ChatSessionSummary)], ['query']),
  'listDocuments' : IDL.Func(
      [DocumentFilter],
      [IDL.Vec(DocumentView)],
      ['query'],
    ),
  'renameDocument' : IDL.Func(
      [DocumentId, IDL.Text],
      [IDL.Opt(DocumentView)],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setExtractedText' : IDL.Func(
      [DocumentId, IDL.Text],
      [IDL.Opt(DocumentDetail)],
      [],
    ),
  'setProcessingFailed' : IDL.Func(
      [DocumentId, IDL.Text],
      [IDL.Opt(DocumentDetail)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ChatSessionId = IDL.Nat;
  const MessageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const DocumentId = IDL.Nat;
  const Citation = IDL.Record({
    'documentName' : IDL.Text,
    'passage' : IDL.Text,
    'documentId' : DocumentId,
    'index' : IDL.Nat,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : MessageRole,
    'citations' : IDL.Vec(Citation),
  });
  const ChatSessionView = IDL.Record({
    'id' : ChatSessionId,
    'title' : IDL.Text,
    'documentIds' : IDL.Vec(DocumentId),
    'messages' : IDL.Vec(Message),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const AskResult = IDL.Record({
    'answer' : Message,
    'session' : ChatSessionView,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileType = IDL.Variant({
    'pdf' : IDL.Null,
    'txt' : IDL.Null,
    'markdown' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ProcessingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'processing' : IDL.Null,
    'ready' : IDL.Null,
    'failed' : IDL.Text,
  });
  const DocumentDetail = IDL.Record({
    'id' : DocumentId,
    'status' : ProcessingStatus,
    'name' : IDL.Text,
    'fileType' : FileType,
    'extractedText' : IDL.Opt(IDL.Text),
    'storageRef' : IDL.Text,
    'sizeBytes' : IDL.Nat,
    'uploadedAt' : Timestamp,
  });
  const ChatSessionSummary = IDL.Record({
    'id' : ChatSessionId,
    'title' : IDL.Text,
    'documentIds' : IDL.Vec(DocumentId),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'messageCount' : IDL.Nat,
  });
  const DocumentFilter = IDL.Record({
    'nameContains' : IDL.Opt(IDL.Text),
    'fileType' : IDL.Opt(FileType),
  });
  const DocumentView = IDL.Record({
    'id' : DocumentId,
    'status' : ProcessingStatus,
    'name' : IDL.Text,
    'fileType' : FileType,
    'hasExtractedText' : IDL.Bool,
    'sizeBytes' : IDL.Nat,
    'uploadedAt' : Timestamp,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'askQuestion' : IDL.Func([ChatSessionId, IDL.Text], [AskResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChatSession' : IDL.Func(
        [IDL.Text, IDL.Vec(DocumentId)],
        [ChatSessionView],
        [],
      ),
    'createDocument' : IDL.Func(
        [IDL.Text, FileType, IDL.Nat, IDL.Text],
        [DocumentId],
        [],
      ),
    'deleteChatSession' : IDL.Func([ChatSessionId], [IDL.Bool], []),
    'deleteDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatSession' : IDL.Func(
        [ChatSessionId],
        [IDL.Opt(ChatSessionView)],
        ['query'],
      ),
    'getDocument' : IDL.Func(
        [DocumentId],
        [IDL.Opt(DocumentDetail)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChatSessions' : IDL.Func([], [IDL.Vec(ChatSessionSummary)], ['query']),
    'listDocuments' : IDL.Func(
        [DocumentFilter],
        [IDL.Vec(DocumentView)],
        ['query'],
      ),
    'renameDocument' : IDL.Func(
        [DocumentId, IDL.Text],
        [IDL.Opt(DocumentView)],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setExtractedText' : IDL.Func(
        [DocumentId, IDL.Text],
        [IDL.Opt(DocumentDetail)],
        [],
      ),
    'setProcessingFailed' : IDL.Func(
        [DocumentId, IDL.Text],
        [IDL.Opt(DocumentDetail)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };