/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AskResult { 'answer' : Message, 'session' : ChatSessionView }
export interface Cell { 'value' : Value, 'name' : string }
export type ChatSessionId = bigint;
export interface ChatSessionSummary {
  'id' : ChatSessionId,
  'title' : string,
  'documentIds' : Array<DocumentId>,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'messageCount' : bigint,
}
export interface ChatSessionView {
  'id' : ChatSessionId,
  'title' : string,
  'documentIds' : Array<DocumentId>,
  'messages' : Array<Message>,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export interface Citation {
  'documentName' : string,
  'passage' : string,
  'documentId' : DocumentId,
  'index' : bigint,
}
export interface DocumentDetail {
  'id' : DocumentId,
  'status' : ProcessingStatus,
  'name' : string,
  'fileType' : FileType,
  'extractedText' : [] | [string],
  'storageRef' : string,
  'sizeBytes' : bigint,
  'uploadedAt' : Timestamp,
}
export interface DocumentFilter {
  'nameContains' : [] | [string],
  'fileType' : [] | [FileType],
}
export type DocumentId = bigint;
export interface DocumentView {
  'id' : DocumentId,
  'status' : ProcessingStatus,
  'name' : string,
  'fileType' : FileType,
  'hasExtractedText' : boolean,
  'sizeBytes' : bigint,
  'uploadedAt' : Timestamp,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type FileType = { 'pdf' : null } |
  { 'txt' : null } |
  { 'markdown' : null };
export interface Message {
  'id' : MessageId,
  'content' : string,
  'createdAt' : Timestamp,
  'role' : MessageRole,
  'citations' : Array<Citation>,
}
export type MessageId = bigint;
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export type ProcessingStatus = { 'pending' : null } |
  { 'processing' : null } |
  { 'ready' : null } |
  { 'failed' : string };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Ask a question in a chat session. The backend retrieves the selected
   * / documents' text, calls Caffeine Inference, and returns the answer with
   * / numbered citations. No API key is collected or stored.
   */
  'askQuestion' : ActorMethod<[ChatSessionId, string], AskResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Start a new chat session bound to the given documents.
   */
  'createChatSession' : ActorMethod<
    [string, Array<DocumentId>],
    ChatSessionView
  >,
  /**
   * / Register an uploaded document. The file bytes are stored via platform
   * / file storage; `storageRef` is the resulting reference.
   */
  'createDocument' : ActorMethod<
    [string, FileType, bigint, string],
    DocumentId
  >,
  /**
   * / Delete one of the caller's chat sessions.
   */
  'deleteChatSession' : ActorMethod<[ChatSessionId], boolean>,
  /**
   * / Delete one of the caller's documents.
   */
  'deleteDocument' : ActorMethod<[DocumentId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch one of the caller's chat sessions with its message history.
   */
  'getChatSession' : ActorMethod<[ChatSessionId], [] | [ChatSessionView]>,
  /**
   * / Fetch one of the caller's documents with its extracted text preview.
   */
  'getDocument' : ActorMethod<[DocumentId], [] | [DocumentDetail]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the caller's chat sessions.
   */
  'listChatSessions' : ActorMethod<[], Array<ChatSessionSummary>>,
  /**
   * / List the caller's documents, optionally filtered by name and file type.
   */
  'listDocuments' : ActorMethod<[DocumentFilter], Array<DocumentView>>,
  /**
   * / Rename one of the caller's documents.
   */
  'renameDocument' : ActorMethod<[DocumentId, string], [] | [DocumentView]>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Store extracted text for a document and mark it ready.
   */
  'setExtractedText' : ActorMethod<[DocumentId, string], [] | [DocumentDetail]>,
  /**
   * / Mark a document's extraction as failed.
   */
  'setProcessingFailed' : ActorMethod<
    [DocumentId, string],
    [] | [DocumentDetail]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];