/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AskResult {
    answer: Message;
    session: ChatSessionView;
}
export interface Cell {
    value: Value;
    name: string;
}
export type ChatSessionId = bigint;
export interface ChatSessionSummary {
    id: ChatSessionId;
    title: string;
    documentIds: Array<DocumentId>;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    messageCount: bigint;
}
export interface ChatSessionView {
    id: ChatSessionId;
    title: string;
    documentIds: Array<DocumentId>;
    messages: Array<Message>;
    createdAt: Timestamp;
    updatedAt: Timestamp;
}
export interface Citation {
    documentName: string;
    passage: string;
    documentId: DocumentId;
    index: bigint;
}
export interface DocumentDetail {
    id: DocumentId;
    status: ProcessingStatus;
    name: string;
    fileType: FileType;
    extractedText?: string;
    storageRef: string;
    sizeBytes: bigint;
    uploadedAt: Timestamp;
}
export interface DocumentFilter {
    nameContains?: string;
    fileType?: FileType;
}
export type DocumentId = bigint;
export interface DocumentView {
    id: DocumentId;
    status: ProcessingStatus;
    name: string;
    fileType: FileType;
    hasExtractedText: boolean;
    sizeBytes: bigint;
    uploadedAt: Timestamp;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Message {
    id: MessageId;
    content: string;
    createdAt: Timestamp;
    role: MessageRole;
    citations: Array<Citation>;
}
export type MessageId = bigint;
export type ProcessingStatus = {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "processing";
    processing: null;
} | {
    __kind__: "ready";
    ready: null;
} | {
    __kind__: "failed";
    failed: string;
};
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum FileType {
    pdf = "pdf",
    txt = "txt",
    markdown = "markdown"
}
export enum MessageRole {
    user = "user",
    assistant = "assistant"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Ask a question in a chat session. The backend retrieves the selected
     * / documents' text, calls Caffeine Inference, and returns the answer with
     * / numbered citations. No API key is collected or stored.
     */
    askQuestion(sessionId: ChatSessionId, question: string): Promise<AskResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Start a new chat session bound to the given documents.
     */
    createChatSession(title: string, documentIds: Array<DocumentId>): Promise<ChatSessionView>;
    /**
     * / Register an uploaded document. The file bytes are stored via platform
     * / file storage; `storageRef` is the resulting reference.
     */
    createDocument(name: string, fileType: FileType, sizeBytes: bigint, storageRef: string): Promise<DocumentId>;
    /**
     * / Delete one of the caller's chat sessions.
     */
    deleteChatSession(id: ChatSessionId): Promise<boolean>;
    /**
     * / Delete one of the caller's documents.
     */
    deleteDocument(id: DocumentId): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch one of the caller's chat sessions with its message history.
     */
    getChatSession(id: ChatSessionId): Promise<ChatSessionView | null>;
    /**
     * / Fetch one of the caller's documents with its extracted text preview.
     */
    getDocument(id: DocumentId): Promise<DocumentDetail | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List the caller's chat sessions.
     */
    listChatSessions(): Promise<Array<ChatSessionSummary>>;
    /**
     * / List the caller's documents, optionally filtered by name and file type.
     */
    listDocuments(filter: DocumentFilter): Promise<Array<DocumentView>>;
    /**
     * / Rename one of the caller's documents.
     */
    renameDocument(id: DocumentId, newName: string): Promise<DocumentView | null>;
    schema(): Promise<string>;
    /**
     * / Store extracted text for a document and mark it ready.
     */
    setExtractedText(id: DocumentId, text: string): Promise<DocumentDetail | null>;
    /**
     * / Mark a document's extraction as failed.
     */
    setProcessingFailed(id: DocumentId, reason: string): Promise<DocumentDetail | null>;
}
import type { AskResult as _AskResult, Cell as _Cell, ChatSessionId as _ChatSessionId, ChatSessionView as _ChatSessionView, Citation as _Citation, DocumentDetail as _DocumentDetail, DocumentFilter as _DocumentFilter, DocumentId as _DocumentId, DocumentView as _DocumentView, Error as _Error, FileType as _FileType, Message as _Message, MessageId as _MessageId, MessageRole as _MessageRole, ProcessingStatus as _ProcessingStatus, Result as _Result, Result__1 as _Result__1, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async askQuestion(arg0: ChatSessionId, arg1: string): Promise<AskResult> {
        if (this.processError) {
            try {
                const result = await this.actor.askQuestion(arg0, arg1);
                return from_candid_AskResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askQuestion(arg0, arg1);
            return from_candid_AskResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChatSession(arg0: string, arg1: Array<DocumentId>): Promise<ChatSessionView> {
        if (this.processError) {
            try {
                const result = await this.actor.createChatSession(arg0, arg1);
                return from_candid_ChatSessionView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChatSession(arg0, arg1);
            return from_candid_ChatSessionView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDocument(arg0: string, arg1: FileType, arg2: bigint, arg3: string): Promise<DocumentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(arg0, to_candid_FileType_n14(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(arg0, to_candid_FileType_n14(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async deleteChatSession(arg0: ChatSessionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChatSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChatSession(arg0);
            return result;
        }
    }
    async deleteDocument(arg0: DocumentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatSession(arg0: ChatSessionId): Promise<ChatSessionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatSession(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatSession(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: DocumentId): Promise<DocumentDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listChatSessions(): Promise<Array<ChatSessionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChatSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChatSessions();
            return result;
        }
    }
    async listDocuments(arg0: DocumentFilter): Promise<Array<DocumentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocuments(to_candid_DocumentFilter_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocuments(to_candid_DocumentFilter_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameDocument(arg0: DocumentId, arg1: string): Promise<DocumentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.renameDocument(arg0, arg1);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameDocument(arg0, arg1);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setExtractedText(arg0: DocumentId, arg1: string): Promise<DocumentDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setExtractedText(arg0, arg1);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setExtractedText(arg0, arg1);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProcessingFailed(arg0: DocumentId, arg1: string): Promise<DocumentDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setProcessingFailed(arg0, arg1);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProcessingFailed(arg0, arg1);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AskResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AskResult): AskResult {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ChatSessionView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatSessionView): ChatSessionView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentDetail_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentDetail): DocumentDetail {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentView_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentView): DocumentView {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FileType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileType): FileType {
    return "pdf" in value ? FileType.pdf : "txt" in value ? FileType.txt : "markdown" in value ? FileType.markdown : value;
}
function from_candid_MessageRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRole): MessageRole {
    return "user" in value ? MessageRole.user : "assistant" in value ? MessageRole.assistant : value;
}
function from_candid_Message_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProcessingStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProcessingStatus): ProcessingStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ChatSessionView]): ChatSessionView | null {
    return value.length === 0 ? null : from_candid_ChatSessionView_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentDetail]): DocumentDetail | null {
    return value.length === 0 ? null : from_candid_DocumentDetail_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentView]): DocumentView | null {
    return value.length === 0 ? null : from_candid_DocumentView_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ChatSessionId;
    title: string;
    documentIds: Array<_DocumentId>;
    messages: Array<_Message>;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
}): {
    id: ChatSessionId;
    title: string;
    documentIds: Array<DocumentId>;
    messages: Array<Message>;
    createdAt: Timestamp;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        title: value.title,
        documentIds: value.documentIds,
        messages: from_candid_vec_n12(_uploadFile, _downloadFile, value.messages),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n17(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n21(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DocumentId;
    status: _ProcessingStatus;
    name: string;
    fileType: _FileType;
    extractedText: [] | [string];
    storageRef: string;
    sizeBytes: bigint;
    uploadedAt: _Timestamp;
}): {
    id: DocumentId;
    status: ProcessingStatus;
    name: string;
    fileType: FileType;
    extractedText?: string;
    storageRef: string;
    sizeBytes: bigint;
    uploadedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_ProcessingStatus_n28(_uploadFile, _downloadFile, value.status),
        name: value.name,
        fileType: from_candid_FileType_n30(_uploadFile, _downloadFile, value.fileType),
        extractedText: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.extractedText)),
        storageRef: value.storageRef,
        sizeBytes: value.sizeBytes,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DocumentId;
    status: _ProcessingStatus;
    name: string;
    fileType: _FileType;
    hasExtractedText: boolean;
    sizeBytes: bigint;
    uploadedAt: _Timestamp;
}): {
    id: DocumentId;
    status: ProcessingStatus;
    name: string;
    fileType: FileType;
    hasExtractedText: boolean;
    sizeBytes: bigint;
    uploadedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_ProcessingStatus_n28(_uploadFile, _downloadFile, value.status),
        name: value.name,
        fileType: from_candid_FileType_n30(_uploadFile, _downloadFile, value.fileType),
        hasExtractedText: value.hasExtractedText,
        sizeBytes: value.sizeBytes,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answer: _Message;
    session: _ChatSessionView;
}): {
    answer: Message;
    session: ChatSessionView;
} {
    return {
        answer: from_candid_Message_n7(_uploadFile, _downloadFile, value.answer),
        session: from_candid_ChatSessionView_n10(_uploadFile, _downloadFile, value.session)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    content: string;
    createdAt: _Timestamp;
    role: _MessageRole;
    citations: Array<_Citation>;
}): {
    id: MessageId;
    content: string;
    createdAt: Timestamp;
    role: MessageRole;
    citations: Array<Citation>;
} {
    return {
        id: value.id,
        content: value.content,
        createdAt: value.createdAt,
        role: from_candid_MessageRole_n9(_uploadFile, _downloadFile, value.role),
        citations: value.citations
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    processing: null;
} | {
    ready: null;
} | {
    failed: string;
}): {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "processing";
    processing: null;
} | {
    __kind__: "ready";
    ready: null;
} | {
    __kind__: "failed";
    failed: string;
} {
    return "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "processing" in value ? {
        __kind__: "processing",
        processing: value.processing
    } : "ready" in value ? {
        __kind__: "ready",
        ready: value.ready
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentView>): Array<DocumentView> {
    return value.map((x)=>from_candid_DocumentView_n35(_uploadFile, _downloadFile, x));
}
function to_candid_DocumentFilter_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentFilter): _DocumentFilter {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_FileType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): _FileType {
    return value == FileType.pdf ? {
        pdf: null
    } : value == FileType.txt ? {
        txt: null
    } : value == FileType.markdown ? {
        markdown: null
    } : value;
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nameContains?: string;
    fileType?: FileType;
}): {
    nameContains: [] | [string];
    fileType: [] | [_FileType];
} {
    return {
        nameContains: value.nameContains ? candid_some(value.nameContains) : candid_none(),
        fileType: value.fileType ? candid_some(to_candid_FileType_n14(_uploadFile, _downloadFile, value.fileType)) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
